[build]
target = "x86_64-unknown-none"
#rustflags = ["-C", "link-arg=-Wl", "-C", "link-arg=-n", "-C", "link-arg=-N", "-C", "link-arg=-static", "-C", "link-arg=-Tlinker.ld"]
rustflags = ["-C", "link-args=-n -N -static -Tlinker.ld"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]